### ISSUE TITLE
css 水平垂直居中

### ISSUE THREAD

**Issue by yanglinyu19930917** [yanglinyu19930917/blog#1]
css的水平垂直居中

```css
 1.grid 方式
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    display:grid;
}
.two{
    justify-self: center;
    align-self: center;
    width: 100px;
    height: 100px;
    border: 1px solid blue;
}
2.  position: relative; +     position: absolute;
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    position: relative;
}
.two{
    width: 100px;
    height: 100px;
    position: absolute;
    border: 1px solid blue;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;

}
3.  position: relative; +  position: absolute;
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    position: relative;
}
.two{
    width: 100px;
    height: 100px;
    border: 1px solid blue;
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -50px;
    margin-left: -50px;
}
4.  position: relative; +   transform: translate(-50%,-50%);
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    position: relative;
}
.two{
    width: 100px;
    height: 100px;
    border: 1px solid blue;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
}
5.flex
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    display:flex;
    justify-content: center;
    align-items: center;

}
.two{
    width: 100px;
    height: 100px;
    border: 1px solid blue;

}
6. margin: 50% auto;

.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    overflow: hidden;
}
.two{
    width: 100px;
    height: 100px;
    margin: 50% auto;
    transform: translateY(-50%);
    border: 1px solid blue;
}
7.  display: table-cell; 
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    display: table-cell;
    text-align: center;
    vertical-align: middle;

}
.two{
    width: 100px;
    height: 100px;
    border: 1px solid blue;
    display: inline-block;

}
8.inline-block + vertical-align
.first{
    width: 400px;
    height: 400px;
    border: 1px solid red;
    text-align: center;
    line-height: 400px;

}
.two{
    width: 100px;
    height: 100px;
    border: 1px solid blue;
    display:inline-block;
    vertical-align: middle;

}

9.不知道宽度和高度的情况下 
1.display: table-cell;
.first{
    width：100%
    heihgt：100%；
    display：table；
}
.two{
    display: table-cell;
    text-align: center;
    vertical-align: middle;
    border: 1px solid blue; 
}
2. flex
 .first{
     width: 100%;
     height: 100%;
     display: flex;
     justify-content: center;
     align-items: center;

}
.two{
    color:#fff;
    font-size: 16px;

}
3.  position: absolute; +    transform:translate(-50%,-50%);
.first{
    position: absolute;
    left: 50%;
    top: 50%;
    transform:translate(-50%,-50%);
    border: 1px solid red;

}
```
